webapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('registreer', views.register, name='register'),
    path('mijn_leerkrachtlijn/', views.theory, name='theory'),
    path('gedeelde_profielen/', views.shared_profiles, name='shared_profiles'),
    path('gedeelde_profielen/profiel', views.view_shared_profile, name='view_shared_profile'),
    path('profiel/', views.profile, name='profile'),
    path('profiel/instellingen', views.profile_settings, name='profile_settings'),
    path('profiel/update_email', views.update_email, name='update_email'),
    path('profiel/deel_profiel', views.share_profile, name='share_profile'),
    path('mijn_leerkrachtlijn/update/primaire_proces', views.update_ps_profile, name='update_ps_profile'),
    path('mijn_leerkrachtlijn/update/brede_professionele_basis', views.update_bpb_profile, name='update_bpb_profile'),
    path('mijn_leerkrachtlijn/update/professionele_identiteit', views.update_pi_profile, name='update_pi_profile'),
    path('mijn_leerkrachtlijn/update/notities', views.update_notes, name='update_notes'),
    path('manage_accounts/', views.manage_accounts, name='manage_accounts'),
    path('manage_accounts/manage_leerlingen/', views.manage_students, name='manage_students'),
    path('manage_accounts/manage_docenten/', views.manage_teachers, name='manage_teachers'),
    path('manage_accounts/leerling_aanmaken/', views.create_students, name='create_students'),
    path('manage_accounts/docent_aanmaken/', views.create_teachers, name='create_teachers'),
    path('wachtwoord_aanpassen/', views.change_password, name='change_password'),
    path('manage_accounts/update_accounts', views.update_active, name='update_active'),
]

webapp/models.py
'''
This file contains all django database models in this project.
A database model is similar to a python class, and corresponds
to a database table with table fields.
'''
from django.conf import settings
from datetime import datetime
from django.db import models


class LKL_Dimension(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=50)
    short_description = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class LKL_Category(models.Model):
    super_category = models.ForeignKey('LKL_Dimension', on_delete=models.CASCADE)
    number = models.IntegerField()
    name = models.CharField(max_length=50)
    short_description = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class LKL_Subcategory(models.Model):
    super_category = models.ForeignKey('LKL_Category', on_delete=models.CASCADE)
    number = models.IntegerField()
    name = models.CharField(max_length=50)
    short_description = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class LKL_Subsubcategory(models.Model):
    super_category = models.ForeignKey('LKL_Subcategory', on_delete=models.CASCADE)
    number = models.IntegerField()
    name = models.CharField(max_length=50)
    short_description = models.CharField(max_length=100)
    description_beginning = models.TextField()
    description_in_development = models.TextField()
    description_starter = models.TextField()
    description_basic_competence = models.TextField()
    description_professional_competence = models.TextField()

    def __str__(self):
        return self.name


class LKL_Resource(models.Model):
    categories = models.ManyToManyField(LKL_Subcategory);
    title = models.CharField(max_length=300)
    upva_resource = models.BooleanField(default=False)
    hva_resource = models.BooleanField(default=False)
    reference = models.CharField(max_length=500)
    resource_URL = models.URLField()
    def __str__(self):
        return self.title


class User_Profile(models.Model):
    profile_owner = models.OneToOneField(settings.AUTH_USER_MODEL,
      related_name='user_profile',
      on_delete=models.CASCADE)
    student_id = models.CharField(max_length=20, blank=True)
    profile_shared_list = models.ManyToManyField(settings.AUTH_USER_MODEL,
      related_name='accessable_user_profile',
      limit_choices_to={'groups__name': 'Docent'}, blank=True)
    def __str__(self):
        return "{}".format(self.profile_owner)


class Category_Notes(models.Model):
    user_profile = models.OneToOneField(User_Profile, on_delete=models.CASCADE)
    cat_a_note = models.TextField(blank=True)
    cat_b_note = models.TextField(blank=True)
    cat_c_note = models.TextField(blank=True)
    cat_d_note = models.TextField(blank=True)
    cat_e_note = models.TextField(blank=True)
    cat_f_note = models.TextField(blank=True)
    cat_g_note = models.TextField(blank=True)

    def __str__(self):
        return "{}".format(self.user_profile.profile_owner)


class Primary_Skills_Profile(models.Model):
    user_profile = models.OneToOneField(User_Profile, on_delete=models.CASCADE)
    NO_LEVEL = 'N'
    BEGINNER = 'B'
    IN_DEVELOPMENT = 'IO'
    STARTER = 'S'
    BASIC_COMPETENCE = 'BC'
    PROFESSIONAL_COMPETENCE = 'PC'
    LEVEL_OPTIONS = [
        (NO_LEVEL, 'Geen niveau'),
        (BEGINNER, 'Beginnend'),
        (IN_DEVELOPMENT, 'In Ontwikkeling'),
        (STARTER, 'Startbekwaam'),
        (BASIC_COMPETENCE, 'Basisbekwaam'),
        (PROFESSIONAL_COMPETENCE, 'Vakbekwaam'),
    ]
    level_A_1_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_A_1_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_A_2_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_A_2_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_A_3_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_A_3_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_B_1_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_B_1_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_B_2_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_B_2_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_B_3_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_B_3_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_C_1_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_C_1_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_C_2_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_C_2_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_C_3_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_C_3_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)

    def __str__(self):
        return "{}".format(self.user_profile.profile_owner)


class Broad_Professional_Basis_Profile(models.Model):
    user_profile = models.OneToOneField(User_Profile, on_delete=models.CASCADE)
    NO_LEVEL = 'N'
    BEGINNER = 'B'
    IN_DEVELOPMENT = 'IO'
    STARTER = 'S'
    BASIC_COMPETENCE = 'BC'
    PROFESSIONAL_COMPETENCE = 'PC'
    LEVEL_OPTIONS = [
        (NO_LEVEL, 'Geen niveau'),
        (BEGINNER, 'Beginnend'),
        (IN_DEVELOPMENT, 'In Ontwikkeling'),
        (STARTER, 'Startbekwaam'),
        (BASIC_COMPETENCE, 'Basisbekwaam'),
        (PROFESSIONAL_COMPETENCE, 'Vakbekwaam'),
    ]
    level_D_1_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_D_1_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_D_2_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_D_2_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_D_3_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_D_3_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_E_1_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_E_1_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_E_2_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_E_2_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_E_3_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_E_3_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_F_1_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_F_1_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_F_2_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_F_2_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_F_3_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_G_1_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_G_1_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_G_2_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_G_2_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_G_3_1 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)
    level_G_3_2 = models.CharField(max_length=2, choices=LEVEL_OPTIONS, default=NO_LEVEL)

    def __str__(self):
        return "{}".format(self.user_profile.profile_owner)


class Professional_Identity_Profile(models.Model):
    user_profile = models.OneToOneField(User_Profile, on_delete=models.CASCADE)
    answer_q1 = models.TextField(blank=True)
    answer_q2 = models.TextField(blank=True)

    def __str__(self):
        return "{}".format(self.user_profile.profile_owner)

webapp/templates/webapp/change_password.html
{% extends "webapp/page_base.html" %}

{% block "page-theme" %}orange-theme{% endblock %}

{% block "page-header" %}
<h1>Verander mijn Instellingen</h1>
{% endblock %}


{% block "main-nav" %}
{% load webapp_tags %}
<li>
  <a href="{% url 'theory'%}">
    Mijn Leer-Kracht-Lijn
  </a>
</li>
{% if request.user|has_group:"Leerling" %}
<li>
  <a href="{% url 'profile' %}">
    Mijn voortgang
  </a>
</li>
{% endif %}
{% if request.user|has_group:"Docent" %}
<li>
  <a href="{% url 'shared_profiles' %}">
    Profielen gedeeld met mij
  </a>
</li>
{% endif %}
{% if request.user.is_superuser %}
<li>
  <a href="{% url 'manage_accounts' %}">
    Manage accounts
  </a>
</li>
{% endif %}

{% endblock %}


{% block "main-content" %}
<article>
  {% if password_changed %}
  <strong>
    Je wachtwoord was met succes veranderd!
  </strong>
  {% endif %}
  <section>
    <header>
      <h1>Email aanpassen</h1>
    </header>
    <form id="edit-email" class="editform column" method="POST">
      {% csrf_token %}
      <p>Huidige email: {{request.user.email}}</p>
      <label for="id_user_email">Nieuwe email</label>
      {{user_form.user_email.errors}}
      <p>{{user_form.user_email}}</p>
      <input type="hidden" name="form" value="emailform">
      <input class="actionbtn" type="submit" value="Email aanpassen">
    </form>
  </section>

  <section>
    <header>
      <h1>Wachtwoord aanpassen</h1>
    </header>

    <form class="column" method="POST">
      {% csrf_token %}
      {{ password_form }}
      <input type="hidden" name="form" value="passwordform">
      <input type="submit" class="actionbtn" value="Wachtwoord aanpassen">
    </form>
  </section>

</article>
{% endblock %}

webapp/templates/webapp/index.html
{% extends "webapp/page_base.html" %}

{% block "page-theme" %} orange-theme {% endblock %}

{% block "page-header" %}
<h1>Hoofdpagina</h1>
{% endblock %}


{% block "main-nav" %}
{% load webapp_tags %}
<li>
  <a href="{% url 'theory'%}">
    Mijn Leer-Kracht-Lijn
  </a>
</li>
{% if request.user|has_group:"Leerling" %}
<li>
  <a href="{% url 'profile' %}">
    Mijn voortgang
  </a>
</li>
{% endif %}
{% if request.user|has_group:"Docent" %}
<li>
  <a href="{% url 'shared_profiles' %}">
    Profielen gedeeld met mij
  </a>
</li>
{% endif %}
{% if request.user.is_superuser %}
<li>
  <a href="{% url 'manage_accounts' %}">
    Manage accounts
  </a>
</li>
{% endif %}
{% endblock %}

{% block "main-content" %}
<article>
  {% load static %}

  <header>
    <h1>Welkom bij jouw eigen Amsterdamse Leer-kracht-lijn.</h1>
  </header>
  <p>
  Deze Leer-Kracht-Lijn helpt jou om jouw eigen ontwikkeling tot leerkracht in
  professionele termen te duiden, onderbouwen en verantwoorden. Het is een
  gespreks- en reflectie instrument. Je maakt jouw eigen ontwikkeling zichtbaar
  via de Leer-Kracht-Lijn voor jezelf en anderen.
  </p>

  <a href="{% url 'theory' %}">
    Op deze pagina kun je meer uitleg vinden over de Amsterdamse Leer-Kracht-Lijn <i class="fas fa-long-arrow-alt-right"></i>
  </a>
  <br><br>

  <figure>
    <img src="{% static 'webapp/img/leerkrachtlijn.png' %}" alt="leerkrachtlijn">
    <caption>De Amsterdamse Leer-Kracht-Lijn bestaat uit drie dimensies. Van rechts naar links: primaire proces; brede professionele basis; professionele identiteit.</caption>
  </figure>
  <br>
  <p>
    De Amsterdamse Leer-Kracht-Lijn wordt gebruikt door de leraaropleidingen van de UPvA en HvA.
  </p>

  <figure>
    <img class="avgimg" src="{% static 'webapp/img/samenopleidenamsterdam.jpg' %}" alt="Samen opleiden in Amsterdam">
  </figure>



</article>
{% endblock %}

webapp/templates/webapp/manage_accounts.html
{% extends "webapp/page_base.html" %}

{% block "page-theme" %} orange-theme {% endblock %}

{% block "page-header" %}
<h1>Accounts managen</h1>
{% endblock %}


{% block "main-nav" %}
{% load webapp_tags %}
<li>
  <a href="{% url 'theory'%}">
    Mijn Leer-Kracht-Lijn
  </a>
</li>
{% if request.user|has_group:"Leerling" %}
<li>
  <a href="{% url 'profile' %}">
    Mijn voortgang
  </a>
</li>
{% endif %}
{% if request.user|has_group:"Docent" %}
<li>
  <a href="{% url 'shared_profiles' %}">
    Profielen gedeeld met mij
  </a>
</li>
{% endif %}
{% if request.user.is_superuser %}
<li>
  <a class="active-nav-link" href="{% url 'manage_accounts' %}">
    Manage accounts
  </a>
</li>
{% endif %}
{% endblock %}

{% block "secondary-nav" %}
<nav id="secondary-nav" class="darktheme">
  <ul id="secondary-nav-links" class="row navbar">
    <li>
      <a class="active-nav-link" href="{% url 'manage_accounts' %}">
        Account overzicht
      </a>
    </li>
    <li>
      <a href="{% url 'manage_students' %}">
        Student toevoegen
      </a>
    </li>
    <li>
      <a href="{% url 'manage_teachers' %}">
        Docent toevoegen
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

{% block "main-content" %}
<article class="content-section">

    <nav class="row darktheme">
      <fieldset class="column">
        <input onkeyup="filterSharedProfiles(true);" id="studentname" type="text" placeholder="Zoek student op naam..">
        <input onkeyup="filterSharedProfiles(true);" id="studentid" type="text" placeholder="Zoek student op studentId..">
      </fieldset>
      <fieldset>
        <div>
          <label for="joined-since">Accounts geregistreerd vanaf:</label>
          <input onchange="filterSharedProfiles(true);" id="joined-since" type="date">
        </div>
        <div>
          <label for="joined-till">Accounts geregistreerd tot:</label>
          <input onchange="filterSharedProfiles(true);" id="joined-till" type="date">
        </div>

      </fieldset>
    </nav>

    <div class="listing-wrapper">
      <ul id="student-overview" class="listing">
        {% for account in accounts %}
        <li>
          <div class="column">
            <span class="name-data">{{account.username}}</span>
            {% if account.user_profile.student_id %}
            <span>
            student id: (<span class="id-data">{{account.user_profile.student_id}}</span>)
            </span>
            {% else %}
            <span class="id-data"></span>
            {% endif %}
            <span>{{account.email}}</span>
          </div>
          <div>
            registratie: <span class="joined-data">{{account.date_joined|date:"d/m/Y"}}</span>
          </div>


          {% if not account.is_superuser %}
          {% if account.is_active %}
          <form action="{% url 'update_active' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{account.pk}}">
            <input class="setinactive" type="submit" name="form" value="Zet op inactief">
          </form>
          {% else %}
          <form action="{% url 'update_active' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{account.pk}}">
            <input class="setactive" type="submit" name="form" value="Zet op actief">
          </form>
          {% endif %}
          {% else %}
          <div>Admin: wijzigen niet mogelijk</div>
          {% endif %}
        </li>
        {% endfor %}
      </ul>
    </div>
</article>

{% endblock %}

webapp/templates/webapp/manage_students.html
{% extends "webapp/page_base.html" %}

{% block "page-theme" %} orange-theme {% endblock %}

{% block "page-header" %}
<h1>Accounts managen</h1>
{% endblock %}


{% block "main-nav" %}
{% load webapp_tags %}
<li>
  <a href="{% url 'theory'%}">
    Mijn Leer-Kracht-Lijn
  </a>
</li>
{% if request.user|has_group:"Leerling" %}
<li>
  <a href="{% url 'profile' %}">
    Mijn voortgang
  </a>
</li>
{% endif %}
{% if request.user|has_group:"Docent" %}
<li>
  <a href="{% url 'shared_profiles' %}">
    Profielen gedeeld met mij
  </a>
</li>
{% endif %}
{% if request.user.is_superuser %}
<li>
  <a class="active-nav-link" href="{% url 'manage_accounts' %}">
    Manage accounts
  </a>
</li>
{% endif %}
{% endblock %}

{% block "secondary-nav" %}
<nav id="secondary-nav" class="darktheme">
  <ul id="secondary-nav-links" class="row navbar">
    <li>
      <a href="{% url 'manage_accounts' %}">
        Account overzicht
      </a>
    </li>
    <li>
      <a class="active-nav-link" href="{% url 'manage_students' %}">
        Student toevoegen
      </a>
    </li>
    <li>
      <a href="{% url 'manage_teachers' %}">
        Docent toevoegen
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

{% block "main-content" %}
<article class="content-section">
  <section>
    <header">
      <h1>Nieuwe student toevoegen</h1>
    </header>
    <form class="column" action="{% url 'create_students' %}" method="POST">
      {% csrf_token %}
      {{form}}
      <input class="actionbtn" type="submit" value="Maak nieuwe student aan">
    </form>
  </section>
</article>
{% endblock %}

webapp/templates/webapp/manage_teachers.html
{% extends "webapp/page_base.html" %}

{% block "page-theme" %} orange-theme {% endblock %}

{% block "page-header" %}
<h1>Accounts managen</h1>
{% endblock %}


{% block "main-nav" %}
{% load webapp_tags %}
<li>
  <a href="{% url 'theory'%}">
    Mijn Leer-Kracht-Lijn
  </a>
</li>
{% if request.user|has_group:"Leerling" %}
<li>
  <a href="{% url 'profile' %}">
    Mijn voortgang
  </a>
</li>
{% endif %}
{% if request.user|has_group:"Docent" %}
<li>
  <a href="{% url 'shared_profiles' %}">
    Profielen gedeeld met mij
  </a>
</li>
{% endif %}
{% if request.user.is_superuser %}
<li>
  <a class="active-nav-link" href="{% url 'manage_accounts' %}">
    Manage accounts
  </a>
</li>
{% endif %}
{% endblock %}

{% block "secondary-nav" %}
<nav id="secondary-nav" class="darktheme">
  <ul id="secondary-nav-links" class="row navbar">
    <li>
      <a href="{% url 'manage_accounts' %}">
        Account overzicht
      </a>
    </li>
    <li>
      <a href="{% url 'manage_students' %}">
        Student toevoegen
      </a>
    </li>
    <li>
      <a class="active-nav-link" href="{% url 'manage_teachers' %}">
        Docent toevoegen
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

{% block "main-content" %}
<article class="content-section">
  <section>
    <header">
      <h1>Nieuwe docent toevoegen</h1>
    </header>
    <form class="column" action="{% url 'create_teachers' %}" method="post">
      {% csrf_token %}
      {{form}}
      <input class="actionbtn" type="submit" value="Maak nieuwe docent aan">
    </form>
  </section>
</article>
{% endblock %}

webapp/templates/webapp/shared_profile.html
{% extends "webapp/page_base.html" %}

{% block "page-theme" %} orange-theme {% endblock %}

{% block "page-header" %}
<h1> Profiel van {{profile.profile_owner}} ({{profile.student_id}})</h1>
{% endblock %}


{% block "main-nav" %}
{% load webapp_tags %}
<li>
  <a href="{% url 'theory'%}">
    Mijn Leer-Kracht-Lijn
  </a>
</li>
{% if request.user|has_group:"Leerling" %}
<li>
  <a href="{% url 'profile' %}">
    Mijn voortgang
  </a>
</li>
{% endif %}
<li>
  <a class="active-nav-link"
     href="{% url 'shared_profiles' %}">
    Profielen gedeeld met mij
  </a>
</li>
{% if request.user.is_superuser %}
<li>
  <a href="{% url 'manage_accounts' %}">
    Manage accounts
  </a>
</li>
{% endif %}
{% endblock %}


{% block "main-content" %}

<section id="ps_charts" class="eval-charts">
  <a href="{% url 'shared_profiles' %}" >
    <i class="fas fa-long-arrow-alt-left"></i> Terug naar overzicht
  </a>
  <header>
    <h1>
      {{dimensions.0.name}}
    </h1>
  </header>
  <div class="row">
  {% for category in dimensions.0.lkl_category_set.all %}
    <button class="tabbtn ps-chart-btn"
            onclick="showTab(this, '.ps-chart-btn', '#ps-chart-{{category.number}}', '.ps-chart')">
      {{ category.name }}
    </button>
  {% endfor %}
  </div>

  <figure id="ps-chart-1" class="ps-chart">
    <canvas width="300" height="300"></canvas>
  </figure>
  <figure id="ps-chart-2" class="ps-chart">
    <canvas width="300" height="300"></canvas>
  </figure>
  <figure id="ps-chart-3" class="ps-chart">
    <canvas width="300" height="300"></canvas>
  </figure>
</section>

<section id="bpb_charts" class="eval-charts">
  <header>
    <h1>
      {{dimensions.1.name}}
    </h1>
  </header>
  <div class="row">
  {% for category in dimensions.1.lkl_category_set.all %}
    <button class="tabbtn bpb-chart-btn"
            onclick="showTab(this, '.bpb-chart-btn', '#bpb-chart-{{category.number}}', '.bpb-chart')">
      {{ category.name }}
    </button>
  {% endfor %}
  </div>

  <figure id="bpb-chart-1" class="bpb-chart">
    <canvas width="300" height="300"></canvas>
  </figure>
  <figure id="bpb-chart-2" class="bpb-chart">
    <canvas width="300" height="300"></canvas>
  </figure>
  <figure id="bpb-chart-3" class="bpb-chart">
    <canvas width="300" height="300"></canvas>
  </figure>
  <figure id="bpb-chart-4" class="bpb-chart">
    <canvas width="300" height="300"></canvas>
  </figure>
</section>

<section id="pi-answers">
  <header>
    <h1>
      {{dimensions.2.name}}
    </h1>
  </header>

  <section>
    <header>
      <h1>Zicht krijgen en reflecteren op mijn identiteit</h1>
    </header>
    <p>
      {{profile.professional_identity_profile.answer_q1}}
    </p>
  </section>

  <section>
    <header>
      <h1>Verhouding van mijn identiteit tot anderen</h1>
    </header>
    <p>
      {{profile.professional_identity_profile.answer_q2}}
    </p>
  </section>
</section>

{% endblock %}


{% block "scripts" %}
{% load static %}
  <script type="text/javascript">
    const levelMapping = {"B" : 1, "IO" : 2, "S" : 3, "BC" : 4, "PC" :5};
    let psLevelValues = {};
    let bpbLevelValues = {};
    {% for section in ps_profile %}
      psLevelValues["{{section.1}}"] = levelMapping["{{section.2}}"];
    {% endfor %}
    {% for section in bpb_profile %}
      bpbLevelValues["{{section.1}}"] = levelMapping["{{section.2}}"];
    {% endfor %}
  </script>
  <script type="text/javascript" src="{% static 'webapp/js/evalGraphs.js' %}"></script>
  <script type="text/javascript">
    const firstPSChartBtn = document.querySelector(".ps-chart-btn");
    const firstBPBChartBtn = document.querySelector(".bpb-chart-btn");
    showTab(firstPSChartBtn, '.ps-chart-btn', '#ps-chart-1', '.ps-chart');
    showTab(firstBPBChartBtn, '.bpb-chart-btn', '#bpb-chart-1', '.bpb-chart');
  </script>
{% endblock %}